Localization = {
	/*This array contains all variables which should be translated to
	Ukrainian before showing.
	*/

	noId: "(немає id)",
	udProps : {
		"Tense": "Час",
		"Number": "Число",
		"Abbr": "Абревіатура",
		"Animacy": "Істота",
		"Aspect": "Вид дієслова",
		"Case": "Відмінок",
		"Degree": "Ступінь порівняння",
		"Foreign": "Запозичене",
		"Gender": "Рід",
		"Hyph": "Складене слово",
		"Mood": "Спосіб",
		"NameType": "Власна назва",
		"NumType": "Тип числа",
		"PartType": "Вид частки",
		"Person": "Особа",
		"Polarity": "Ствердність",
		"Poss": "Присвійність",
		"PronType": "Тип ",
		"PunctType": "Займенниковий тип",
		"Reflex": "Рефлективність",
		"VerbForm": "Дієслівна форма",
		"Voice": "Стан"
	},
	udValues: {
		"Pres": "Теперішній",
		"Past": "Минулий",
		"Fut": "Майбутній",
		"Sing": "Однина",
		"Plur": "Множина",
		"Dual": "Двоїна",
		"Ptan": "Парне",
		"Abs": "Найвищий складений",
		"Acc": "Знахідний",
		"active": "Дійсний",
		"Anim": "Жива",
		"Card": "Прості",
		"Com": "Спільний",
		"Cmp": "Вищий",
		"Cnd": "Умовний",
		"conseq": "Пояснювальна",
		"Dat": "Давальний",
		"demonstrative": "Вказівний",
		"Fem": "Жіночий",
		"finite verb": "Способове",
		"first person": "Перша особа",
		"Frac": "Дробові",
		"Geo": "Географічна",
		"Gen": "Родовий",
		"Hab": "Теперішній простий",
		"Hum": "Людська",
		"Imp": "Наказовий",// MOOD
		"Imp": "Інфінітив",
		"Inan": "Нежива",
		"indefinite pronominal": "Невизначений",
		"Ind": "Дійсний",
		"infinitive": "Інфінітив",
		"Ins": "Орудний",
		"interrogative": "Питальний",
		"Iter": "Повторювана дія",
		"Loc": "Місцевий",
		"Masc": "Чоловіча",
		"Mult": "Множинні",
		"negative pronominal": "Заперечний",
		"Nat": "Національність",
		"Neut": "Середній",
		"Nom": "Називний",
		"Nhum": "Не людська",
		"Opt": "Бажальний",
		"Ord": "Порядкові",
		"Oth": "Інше",
		"participle": "Дієприслівник",
		"passive": "Пасивний",
		"Perf": "Доконаний",
		"Prs": "Ім’я людини",
		"personal": "Присвійний",
		"Pos": "Якісний",
		"Prog": "Недоконаний",
		"Prp": "Спонукальний",
		"relative": "Відносний",
		"second person": "Друга особа",
		"Sets": "Для незлічуваних",
		"Sur": "Прізвище",
		"Sup": "Найвищий",
		"third person": "Третя особа",
		"total": "Збірний",
		"Voc": "Кличний"
	}
}
