Localization = {
	/*This array contains all variables which should be translated to
	Ukrainian before showing.
	*/

	noId: "(немає id)",
	udProps : {
		"Tense": "Час",
		"Number": "Число",
		"Abbr": "Чи абревіатура",
		"Animacy": "Істота",
		"Aspect": "Вид дієслова",
		"Case": "Відмінок",
		"Degree": "Ступінь порівняння",
		"Foreign": "Чи запозичене",
		"Gender": "Рід",
		"Hyph": "Чи складене",
		"Mood": "Спосіб",
		"NameType": "Власна назва",
		"NumType": "Тип числа",
		"PartType": "Вид частки",
		"Person": "Особа",
		"Polarity": "Ствердність",
		"Poss": "Присвійність",
		"PronType": "Займенниковий тип",
		"PunctType": "Пунктуація",
		"Reflex": "Чи зворотнє",
		"VerbForm": "Дієслівна форма",
		"Voice": "Стан"
	},
	udValues: {
		"Tense.Pres": "Теперішній",
		"Tense.Past": "Минулий",
		"Tense.Fut": "Майбутній",
		"Number.Sing": "Однина",
		"Number.Plur": "Множина",
		"Number.Dual": "Двоїна",
		"Number.Ptan": "Парне",
		"Degree.Abs": "Найвищий складений",
		"Case.Acc": "Знахідний",
		"Voice.Act": "Дійсний",
		"Animacy.Anim": "Жива",
		"NumType.Card": "Прості",
		"Gender.Com": "Спільний",
		"Degree.Cmp": "Вищий",
		"Mood.Cnd": "Умовний",
		"PartType.Conseq": "Пояснювальна",
		"Case.Dat": "Давальний",
		"PronType.Dem": "Вказівний",
		"Gender.Fem": "Жіночий",
		"VerbForm.Fin": "Способове",
		"Person.1": "Перша особа",
		"NumType.Frac": "Дробові",
		"NameType.Geo": "Географічна",
		"Case.Gen": "Родовий",
		"Aspect.Hab": "Теперішній простий",
		"Animacy.Hum": "Людина",
		"Aspect.Imp": "Недоконаний",
		"Mood.Imp": "Наказовий",
		"Tense.Imp": "Інфінітив",
		"Animacy.Inan": "Ні",
		"PronType.Ind": "Невизначений",
		"Mood.Ind": "Дійсний",
		"VerbForm.Inf": "Інфінітив",
		"Case.Ins": "Орудний",
		"PronType.Int": "Питальний",
		"Aspect.Iter": "Повторювана дія",
		"Case.Loc": "Місцевий",
		"Gender.Masc": "Чоловічий",
		"NumType.Mult": "Множинні",
		"Polarity.Neg": "Заперечна",
		"Gender.Neut": "Середній",
		"Case.Nom": "Називний",
		"Animacy.Nhum": "Не людина",
		"Mood.Opt": "Бажальний",
		"NumType.Ord": "Порядкові",
		"VerbForm.Part": "Дієприслівник",
		"Voice.Pass": "Пасивний",
		"Aspect.Perf": "Доконаний",
		"NameType.Prs": "Ім’я людини",
		"PronType.Prs": "Присвійний",
		"Degree.Pos": "Базовий",
		"Polarity.Pos": "Позитивна",
		"Aspect.Prog": "Недоконаний",
		"Mood.Prp": "Спонукальний",
		"PronType.Rel": "Відносний",
		"Person.2": "Друга особа",
		"NumType.Sets": "Незлічуване",
		"NameType.Sur": "Прізвище",
		"Degree.Sup": "Найвищий",
		"Person.3": "Третя особа",
		"PronType.Tot": "Збірний",
		"Case.Voc": "Кличний",
		"PunctType.Qest": "Знак питання",
		"PunctType.Excl": "Знак оклику",
		"PunctType.Quot": "Лапки",
		"PunctType.Brck": "Дужки",
		"PunctType.Comm": "Кома",
		"PunctType.Colo": "Двокрапка",
		"PunctType.Semi": "Крапка з комою",
		"PunctType.Dash": "Тире, дефіс",
		"PunctType.Symb": "Символ",
		"PunctType.Peri": "Крапка",
		"Abbr.Yes": "Так",
		"Foreign.Yes": "Так",
		"Hyph.Yes": "Так",
		"Poss.Yes": "Так",
		"Reflex.Yes": "Так"
	}
}
